# Generated by Django 5.1.4 on 2024-12-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_ege1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='password',
            field=models.CharField(default='12345678', max_length=20),
        ),
    ]
