# Generated by Django 5.1.4 on 2024-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_ege1', '0002_persons_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_to_stady',
            name='stady',
        ),
        migrations.RemoveField(
            model_name='video_to_stady',
            name='stady',
        ),
        migrations.AlterField(
            model_name='persons',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Text_and_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('original_text_url', models.CharField(max_length=50)),
                ('original_video_url', models.CharField(max_length=50)),
                ('stady', models.ManyToManyField(related_name='text', to='helper_ege1.persons')),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Text_to_stady',
        ),
        migrations.DeleteModel(
            name='Video_to_stady',
        ),
    ]
